# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtApp\alt_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.Qt import  QApplication,QFrame,Qt
import sys
import images_resource


class Ui_Alt_Panel(object):
    def setupUi(self, Alt_Panel):
        Alt_Panel.setObjectName("Alt_Panel")
        Alt_Panel.resize(360, 240)
        Alt_Panel.setStyleSheet("#Alt_Panel{\n"
"border-image: url(:/panel);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"\n"
"}")
        Alt_Panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Alt_Panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Alt_Panel)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.big_frame = QtWidgets.QFrame(Alt_Panel)
        self.big_frame.setStyleSheet("#big_frame{\n"
"border-image: url(:/panel);\n"
"}")
        self.big_frame.setObjectName("big_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.big_frame)
        self.verticalLayout.setContentsMargins(20, 22, 17, 14)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView = QtWidgets.QTreeView(self.big_frame)
        self.treeView.setStyleSheet("QHeaderView::section { \n"
"height:23px; \n"
"color:rgb(194, 167, 93);\n"
"    border-image: url(:/images/label_4.png);\n"
"/*border-left:0px solid gray; \n"
"border-right:1px solid gray; \n"
"border-top:0px solid gray; \n"
"border-bottom:0px solid gray;*/\n"
" }\n"
"\n"
"\n"
"#treeView{\n"
"border-image: url(:/images/label_3.png);\n"
"}\n"
"QTreeView::item{\n"
"height:30px;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"background-color: rgb(85, 255, 127);\n"
"}")
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.frame = QtWidgets.QFrame(self.big_frame)
        self.frame.setMinimumSize(QtCore.QSize(0, 42))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 2, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_alt_add = QtWidgets.QToolButton(self.frame)
        self.btn_alt_add.setMinimumSize(QtCore.QSize(32, 32))
        self.btn_alt_add.setStyleSheet("#btn_alt_add {\n"
"border-image: url(:/add);\n"
"}\n"
"\n"
"#btn_alt_add:hover {\n"
"border-image: url(:/add_h);\n"
"}")
        self.btn_alt_add.setText("")
        self.btn_alt_add.setObjectName("btn_alt_add")
        self.horizontalLayout.addWidget(self.btn_alt_add)
        self.btn_alt_begin = QtWidgets.QToolButton(self.frame)
        self.btn_alt_begin.setMinimumSize(QtCore.QSize(32, 32))
        self.btn_alt_begin.setStyleSheet("#btn_alt_begin{\n"
"border-image: url(:/stop);\n"
"}\n"
"#btn_alt_begin:hover{\n"
"border-image: url(:/stop_h);\n"
"}\n"
"#btn_alt_begin:pressed{\n"
"border-image: url(:/begin_h);\n"
"}")
        self.btn_alt_begin.setText("")
        self.btn_alt_begin.setObjectName("btn_alt_begin")
        self.horizontalLayout.addWidget(self.btn_alt_begin)
        self.btn_alt_delete = QtWidgets.QToolButton(self.frame)
        self.btn_alt_delete.setMinimumSize(QtCore.QSize(32, 32))
        self.btn_alt_delete.setStyleSheet("#btn_alt_delete {\n"
"border-image: url(:/delete);\n"
"}\n"
"#btn_alt_delete:hover {\n"
"border-image: url(:/delete_h);\n"
"}\n"
"#btn_alt_delete:pressed {\n"
"border-image: url(:/delete_p);\n"
"}")
        self.btn_alt_delete.setText("")
        self.btn_alt_delete.setObjectName("btn_alt_delete")
        self.horizontalLayout.addWidget(self.btn_alt_delete)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_2.addWidget(self.big_frame)

        self.retranslateUi(Alt_Panel)
        QtCore.QMetaObject.connectSlotsByName(Alt_Panel)

    def retranslateUi(self, Alt_Panel):
        _translate = QtCore.QCoreApplication.translate
        Alt_Panel.setWindowTitle(_translate("Alt_Panel", "Frame"))
        self.btn_alt_add.setShortcut(_translate("Alt_Panel", "Ctrl+A"))
        self.btn_alt_begin.setShortcut(_translate("Alt_Panel", "Ctrl+Space"))
        self.btn_alt_delete.setShortcut(_translate("Alt_Panel", "Ctrl+Del"))
