# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtApp\display_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.Qt import  QApplication,QFrame,Qt
import sys
import images_resource


class Ui_Display_Panel(object):
    def setupUi(self, Display_Panel):
        Display_Panel.setObjectName("Display_Panel")
        Display_Panel.resize(360, 240)
        Display_Panel.setStyleSheet("#Display_Panel{\n"
"border-image: url(:/panel);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"\n"
"}")
        Display_Panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Display_Panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(Display_Panel)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridFrame = QtWidgets.QFrame(Display_Panel)
        self.gridFrame.setStyleSheet("#gridFrame{\n"
"border-image: url(:/panel);\n"
"}")
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setContentsMargins(19, -1, -1, -1)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_next = QtWidgets.QToolButton(self.gridFrame)
        self.btn_next.setMaximumSize(QtCore.QSize(32, 32))
        self.btn_next.setStyleSheet("#btn_next{\n"
"border-image: url(:/next);\n"
"}")
        self.btn_next.setText("")
        self.btn_next.setObjectName("btn_next")
        self.gridLayout.addWidget(self.btn_next, 2, 1, 1, 1)
        self.btn_clear = QtWidgets.QToolButton(self.gridFrame)
        self.btn_clear.setMaximumSize(QtCore.QSize(32, 32))
        self.btn_clear.setStyleSheet("#btn_clear {\n"
"border-image: url(:/clear);\n"
"}\n"
"\n"
"#btn_clear:pressed {\n"
"border-image: url(:/clear_p);\n"
"}")
        self.btn_clear.setText("")
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout.addWidget(self.btn_clear, 3, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 68))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(164, 136, 77);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lcd_day = QtWidgets.QLCDNumber(self.frame_3)
        self.lcd_day.setStyleSheet("border-image: url(:/images/label_2.png);")
        self.lcd_day.setProperty("intValue", 200)
        self.lcd_day.setObjectName("lcd_day")
        self.horizontalLayout_3.addWidget(self.lcd_day)
        self.gridLayout.addWidget(self.frame_3, 3, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(100, 45))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(189, 161, 97);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lcd_minute = QtWidgets.QLCDNumber(self.frame)
        self.lcd_minute.setStyleSheet("border-image: url(:/images/label_2.png);")
        self.lcd_minute.setObjectName("lcd_minute")
        self.horizontalLayout.addWidget(self.lcd_minute)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_2.setBaseSize(QtCore.QSize(0, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(175, 152, 92);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lcd_hour = QtWidgets.QLCDNumber(self.frame_2)
        self.lcd_hour.setStyleSheet("border-image: url(:/images/label_2.png);")
        self.lcd_hour.setObjectName("lcd_hour")
        self.horizontalLayout_2.addWidget(self.lcd_hour)
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 1)
        self.lnd_name = QtWidgets.QLineEdit(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnd_name.sizePolicy().hasHeightForWidth())
        self.lnd_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lnd_name.setFont(font)
        self.lnd_name.setStyleSheet("QLineEdit {\n"
"background-color: rgba(255, 255, 255, 0);\n"
"    color: rgb(182, 151, 89);\n"
"}")
        self.lnd_name.setFrame(False)
        self.lnd_name.setObjectName("lnd_name")
        self.gridLayout.addWidget(self.lnd_name, 0, 0, 1, 2)
        self.chb_beginStop = QtWidgets.QCheckBox(self.gridFrame)
        self.chb_beginStop.setStyleSheet("QCheckBox::indicator {\n"
"border-image: url(:/stop);\n"
"width: 32px;\n"
"height: 32px;}\n"
"QCheckBox::indicator:checked {\n"
"border-image: url(:/begin);\n"
"}")
        self.chb_beginStop.setText("")
        self.chb_beginStop.setObjectName("chb_beginStop")
        self.gridLayout.addWidget(self.chb_beginStop, 1, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.gridFrame)

        self.retranslateUi(Display_Panel)
        QtCore.QMetaObject.connectSlotsByName(Display_Panel)

    def retranslateUi(self, Display_Panel):
        _translate = QtCore.QCoreApplication.translate
        Display_Panel.setWindowTitle(_translate("Display_Panel", "Frame"))
        self.btn_next.setShortcut(_translate("Display_Panel", "Ctrl+N"))
        self.btn_clear.setShortcut(_translate("Display_Panel", "Ctrl+S"))
        self.label_5.setText(_translate("Display_Panel", "D:"))
        self.label.setText(_translate("Display_Panel", "M:"))
        self.label_3.setText(_translate("Display_Panel", "H:"))
        self.lnd_name.setText(_translate("Display_Panel", "hyh"))
        self.chb_beginStop.setShortcut(_translate("Display_Panel", "Ctrl+Space"))
