# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtApp\down_toolbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.Qt import  QApplication,QFrame,Qt
from PyQt5 import QtWidgets,QtCore
from PyQt5.QtCore import QSize
import sys
import images_resource


class Ui_Down_ToolBar(object):
    def setupUi(self, Down_ToolBar):
        Down_ToolBar.setObjectName("Down_ToolBar")
        Down_ToolBar.resize(260, 60)
        Down_ToolBar.setStyleSheet("#Down_ToolBar\n"
"{border-image: url(:/down);}")
        Down_ToolBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Down_ToolBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(Down_ToolBar)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Down_ToolBar)
        self.widget.setObjectName("widget")
        self.widget.setStyleSheet("#widget{"
                                "border-image: url(:/down);"
                                "}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(8, 0, 8, 14)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_down_read = QtWidgets.QToolButton(self.widget)
        self.btn_down_read.setMinimumSize(QtCore.QSize(32, 32))
        self.btn_down_read.setStyleSheet("QToolButton{\n"
"border-image: url(:/images/read.png);\n"
"}\n"
"QToolButton:hover{\n"
"border-image: url(:/images/read_h.png);\n"
"}\n"
"")
        self.btn_down_read.setText("")
        self.btn_down_read.setObjectName("btn_down_read")
        self.horizontalLayout.addWidget(self.btn_down_read)
        self.btn_down_out = QtWidgets.QToolButton(self.widget)
        self.btn_down_out.setMinimumSize(QtCore.QSize(32, 32))
        self.btn_down_out.setStyleSheet("QToolButton{\n"
"border-image: url(:/images/out.png);\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"border-image: url(:/images/out_h.png);\n"
"}")
        self.btn_down_out.setText("")
        self.btn_down_out.setObjectName("btn_down_out")
        self.horizontalLayout.addWidget(self.btn_down_out)
        self.btn_down_chart = QtWidgets.QToolButton(self.widget)
        self.btn_down_chart.setMinimumSize(QtCore.QSize(32, 32))
        self.btn_down_chart.setStyleSheet("QToolButton{\n"
"border-image: url(:/images/chart.png);\n"
"}\n"
"QToolButton:hover{\n"
"border-image: url(:/images/chart_h.png);\n"
"}")
        self.btn_down_chart.setText("")
        self.btn_down_chart.setObjectName("btn_down_chart")
        self.horizontalLayout.addWidget(self.btn_down_chart)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Down_ToolBar)
        QtCore.QMetaObject.connectSlotsByName(Down_ToolBar)

    def retranslateUi(self, Down_ToolBar):
        _translate = QtCore.QCoreApplication.translate
        Down_ToolBar.setWindowTitle(_translate("Down_ToolBar", "Frame"))
