# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtApp\main_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.Qt import  QApplication,QFrame,Qt
import sys
import images_resource


class Ui_Main_Frame(object):
    def setupUi(self, Main_Frame):
        Main_Frame.setObjectName("Main_Frame")
        Main_Frame.resize(454, 328)
        Main_Frame.setMinimumSize(QtCore.QSize(454, 328))
        Main_Frame.setMaximumSize(QtCore.QSize(454, 328))
        Main_Frame.setStyleSheet("#Main_Frame {\n"
"border-image: url(:/add_h);\n"
"}")
        # Main_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        # Main_Frame.setFrameShadow(QtWidgets.QFrame.Plain)
        # Main_Frame.setLineWidth(1)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Main_Frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Main_Frame)
        self.widget.setStyleSheet("#widget {\n"
"border-image: url(:/back);\n"
"}")
        self.widget.setObjectName("widget")
        self.btn_displayTools = QtWidgets.QToolButton(self.widget)
        self.btn_displayTools.setGeometry(QtCore.QRect(417, 81, 22, 167))
        self.btn_displayTools.setStyleSheet("QToolButton{\n"
"border-image: url(:/images/btn_displayTools.png);\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"border-image: url(:/images/btn_displayTools_h.png);\n"
"}\n"
"QToolButton:pressed{\n"
"border-image: url(:/images/btn_displayTools_h.png);\n"
"}")
        self.btn_displayTools.setText("")
        self.btn_displayTools.setObjectName("btn_displayTools")
        self.btn_functionTools_2 = QtWidgets.QToolButton(self.widget)
        self.btn_functionTools_2.setGeometry(QtCore.QRect(92, 297, 267, 19))
        self.btn_functionTools_2.setStyleSheet("QToolButton{\n"
"border-image: url(:/images/btn_functionTools.png);\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"border-image: url(:/images/btn_functionTools_h.png);\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"border-image: url(:/images/btn_functionTools_h.png);\n"
"}")
        self.btn_functionTools_2.setText("")
        self.btn_functionTools_2.setObjectName("btn_functionTools_2")
        self.btn_upperItems = QtWidgets.QToolButton(self.widget)
        self.btn_upperItems.setGeometry(QtCore.QRect(92, 10, 268, 17))
        self.btn_upperItems.setStyleSheet("QToolButton{\n"
"border-image: url(:/images/btn_upperItem.png);\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"border-image: url(:/images/btn_upperItem_h.png);\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"border-image: url(:/images/btn_upperItem_h.png);\n"
"}")
        self.btn_upperItems.setText("")
        self.btn_upperItems.setObjectName("btn_upperItems")
        self.wgt_centralWidget = QtWidgets.QWidget(self.widget)
        self.wgt_centralWidget.setGeometry(QtCore.QRect(43, 45, 361, 235))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_centralWidget.sizePolicy().hasHeightForWidth())
        self.wgt_centralWidget.setSizePolicy(sizePolicy)
        self.wgt_centralWidget.setObjectName("wgt_centralWidget")
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Main_Frame)
        QtCore.QMetaObject.connectSlotsByName(Main_Frame)

    def retranslateUi(self, Main_Frame):
        _translate = QtCore.QCoreApplication.translate
        Main_Frame.setWindowTitle(_translate("Main_Frame", "Frame"))
        self.btn_displayTools.setShortcut(_translate("Main_Frame", "Ctrl+D"))
        self.btn_functionTools_2.setShortcut(_translate("Main_Frame", "Ctrl+F"))
        self.btn_upperItems.setShortcut(_translate("Main_Frame", "Ctrl+U"))

if __name__=="__main__":
    app=QApplication(sys.argv)
    f = QFrame()

    p=Ui_Main_Frame()
    p.setupUi(f)
    f.setWindowFlags(Qt.FramelessWindowHint)
    f.setAttribute(Qt.WA_TranslucentBackground)
    f.show()
    sys.exit(app.exec_())