# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtApp\right_toolbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.Qt import  QApplication,QFrame,Qt
import sys
import images_resource


class Ui_Right_ToolBar(object):
    def setupUi(self, Right_ToolBar):
        Right_ToolBar.setObjectName("Right_ToolBar")
        Right_ToolBar.resize(50, 153)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Right_ToolBar.sizePolicy().hasHeightForWidth())
        Right_ToolBar.setSizePolicy(sizePolicy)
        Right_ToolBar.setMinimumSize(QtCore.QSize(30, 0))
        Right_ToolBar.setMaximumSize(QtCore.QSize(50, 16777215))
        Right_ToolBar.setStyleSheet("#Right_ToolBar{border-image: url(:/right);}")
        Right_ToolBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        Right_ToolBar.setFrameShadow(QtWidgets.QFrame.Plain)
        Right_ToolBar.setLineWidth(0)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Right_ToolBar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalWidget = QtWidgets.QWidget(Right_ToolBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.verticalWidget.setStyleSheet("#verticalWidget{\n"
"border-image: url(:/right);\n"
"}")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(1, 16, 0, 15)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_right_hide = QtWidgets.QToolButton(self.verticalWidget)
        self.btn_right_hide.setMinimumSize(QtCore.QSize(32, 32))
        self.btn_right_hide.setStyleSheet("#btn_right_hide{\n"
"border-image: url(:/images/eye.png);\n"
"}\n"
"#btn_right_hide:hover{\n"
"border-image: url(:/images/eye_h.png);\n"
"}\n"
"#btn_right_hide:pressed{\n"
"border-image: url(:/images/eye_p.png);\n"
"}")
        self.btn_right_hide.setText("")
        self.btn_right_hide.setObjectName("btn_right_hide")
        self.verticalLayout.addWidget(self.btn_right_hide)
        self.btn_right_relocate = QtWidgets.QToolButton(self.verticalWidget)
        self.btn_right_relocate.setMinimumSize(QtCore.QSize(32, 32))
        self.btn_right_relocate.setStyleSheet("QToolButton{\n"
"border-image: url(:/images/location.png);\n"
"}\n"
"QToolButton:hover{\n"
"border-image: url(:/images/location_p.png);\n"
"}")
        self.btn_right_relocate.setText("")
        self.btn_right_relocate.setObjectName("btn_right_relocate")
        self.verticalLayout.addWidget(self.btn_right_relocate)
        self.btn_right_close = QtWidgets.QToolButton(self.verticalWidget)
        self.btn_right_close.setMinimumSize(QtCore.QSize(32, 32))
        self.btn_right_close.setStyleSheet("QToolButton{\n"
"border-image: url(:/images/x.png);\n"
"}\n"
"QToolButton:hover{\n"
"border-image: url(:/images/x_p.png);\n"
"}")
        self.btn_right_close.setText("")
        self.btn_right_close.setObjectName("btn_right_close")
        self.verticalLayout.addWidget(self.btn_right_close)
        self.verticalLayout_2.addWidget(self.verticalWidget)

        self.retranslateUi(Right_ToolBar)
        QtCore.QMetaObject.connectSlotsByName(Right_ToolBar)

    def retranslateUi(self, Right_ToolBar):
        _translate = QtCore.QCoreApplication.translate
        Right_ToolBar.setWindowTitle(_translate("Right_ToolBar", "Frame"))
        self.btn_right_relocate.setShortcut(_translate("Right_ToolBar", "Ctrl+L"))
        self.btn_right_close.setShortcut(_translate("Right_ToolBar", "Esc"))


if __name__=="__main__":
    app=QApplication(sys.argv)
    f = QFrame()

    p=Ui_Right_ToolBar()
    p.setupUi(f)
    f.setWindowFlags(Qt.FramelessWindowHint)
    f.setAttribute(Qt.WA_TranslucentBackground)
    f.show()
    sys.exit(app.exec_())