# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtApp\up_display.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.Qt import  QApplication,QFrame,Qt
import sys
import images_resource


class Ui_Up_Display(object):
    def setupUi(self, Up_Display):
        Up_Display.setObjectName("Up_Display")
        Up_Display.resize(260, 188)
        Up_Display.setStyleSheet("#Up_Display{\n"
"border-image: url(:/images/fatherTimer_drawer_up_2.png);\n"
"}")
        Up_Display.setFrameShape(QtWidgets.QFrame.NoFrame)
        Up_Display.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Up_Display)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Up_Display)
        self.widget.setStyleSheet("#widget{\n"
"border-image: url(:/images/fatherTimer_drawer_up_2.png);\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(42, 25, 45, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(189, 161, 96);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cbb_upperItem = QtWidgets.QComboBox(self.widget)
        self.cbb_upperItem.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cbb_upperItem.setFont(font)
        self.cbb_upperItem.setStyleSheet("\n"
"/* 未下拉时，QComboBox的样式 */\n"
"QComboBox {\n"
"border-image: url(:/images/label_2.png);\n"
"font: 13pt \"Arial\";\n"
"\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"background-color: rgb(58, 43, 87);\n"
"}\n"
"\n"
"\n"
"/* 下拉后，整个下拉窗体每项的样式 */\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"border-image: url(:/images/listbox_back.png);\n"
"/*QFont font ( “Microsoft YaHei”,15,100); */\n"
"}\n"
"\n"
"\n"
"/* 下拉框样式 */\n"
"QComboBox::drop-down {\n"
"background-color: rgba(255, 255, 255, 0);\n"
"width: 62px\n"
"}\n"
"\n"
"/* 下拉箭头样式 */ QComboBox::down-arrow {\n"
"background-color: rgba(255, 255, 255, 0);\n"
"width:23px;\n"
"height:18px;\n"
"}\n"
"\n"
" QComboBox::down-arrow:pressed {\n"
"border-image: url(:/images/listbox_btn_pressed.png);\n"
"width:23px;\n"
"height:18px;\n"
"}\n"
"\n"
"")
        self.cbb_upperItem.setFrame(False)
        self.cbb_upperItem.setObjectName("cbb_upperItem")
        # self.cbb_upperItem.addItem("")
        # self.cbb_upperItem.addItem("")
        # self.cbb_upperItem.addItem("")
        # self.cbb_upperItem.addItem("")
        # self.cbb_upperItem.addItem("")
        # self.cbb_upperItem.addItem("")
        # self.cbb_upperItem.addItem("")
        # self.cbb_upperItem.addItem("")
        # self.cbb_upperItem.addItem("")
        # self.cbb_upperItem.addItem("")
        # self.cbb_upperItem.addItem("")
        # self.cbb_upperItem.addItem("")
        # self.cbb_upperItem.addItem("")
        self.verticalLayout.addWidget(self.cbb_upperItem)
        self.cbb_dispalyMethod = QtWidgets.QComboBox(self.widget)
        self.cbb_dispalyMethod.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cbb_dispalyMethod.setStyleSheet("\n"
"/* 未下拉时，QComboBox的样式 */\n"
"QComboBox {\n"
"color: rgb(189, 161, 91);\n"
"font: 13pt \"Arial\";\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"background-color: rgb(58, 43, 87);\n"
"}\n"
"\n"
"\n"
"/* 下拉后，整个下拉窗体被选择的每项的样式 */\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"color: rgb(55, 42, 82);\n"
"}\n"
"\n"
"/* 下拉框样式 */\n"
"QComboBox::drop-down {\n"
"\n"
"}\n"
"\n"
"/* 下拉箭头样式 */ QComboBox::down-arrow {\n"
"width:23px;\n"
"height:18px;\n"
"}\n"
"\n"
" QComboBox::down-arrow:pressed {\n"
"\n"
"}\n"
"")
        self.cbb_dispalyMethod.setFrame(False)
        self.cbb_dispalyMethod.setObjectName("cbb_dispalyMethod")
        self.cbb_dispalyMethod.addItem("")
        self.cbb_dispalyMethod.addItem("")
        self.cbb_dispalyMethod.addItem("")
        self.verticalLayout.addWidget(self.cbb_dispalyMethod)
        self.lcd = QtWidgets.QLCDNumber(self.widget)
        self.lcd.setStyleSheet("border-image: url(:/images/label_2.png);")
        self.lcd.setProperty("intValue", 100)
        self.lcd.setObjectName("lcd")
        self.verticalLayout.addWidget(self.lcd)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Up_Display)
        QtCore.QMetaObject.connectSlotsByName(Up_Display)

    def retranslateUi(self, Up_Display):
        _translate = QtCore.QCoreApplication.translate
        Up_Display.setWindowTitle(_translate("Up_Display", "Frame"))
        self.label.setText(_translate("Up_Display", "父项目:"))
        # self.cbb_upperItem.setItemText(0, _translate("Up_Display", "     新建项  目"))
        # self.cbb_upperItem.setItemText(1, _translate("Up_Display", "新建项目"))
        # self.cbb_upperItem.setItemText(2, _translate("Up_Display", "新建项目"))
        # self.cbb_upperItem.setItemText(3, _translate("Up_Display", "新建项目"))
        # self.cbb_upperItem.setItemText(4, _translate("Up_Display", "新建项目"))
        # self.cbb_upperItem.setItemText(5, _translate("Up_Display", "新建项目"))
        # self.cbb_upperItem.setItemText(6, _translate("Up_Display", "新建项目"))
        # self.cbb_upperItem.setItemText(7, _translate("Up_Display", "新建项目"))
        # self.cbb_upperItem.setItemText(8, _translate("Up_Display", "新建项目"))
        # self.cbb_upperItem.setItemText(9, _translate("Up_Display", "新建项目"))
        # self.cbb_upperItem.setItemText(10, _translate("Up_Display", "新建项目"))
        # self.cbb_upperItem.setItemText(11, _translate("Up_Display", "新建项目"))
        # self.cbb_upperItem.setItemText(12, _translate("Up_Display", "新建项目"))
        self.cbb_dispalyMethod.setItemText(0, _translate("Up_Display", "D:"))
        self.cbb_dispalyMethod.setItemText(1, _translate("Up_Display", "H:"))
        self.cbb_dispalyMethod.setItemText(2, _translate("Up_Display", "M:"))
